spring:
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    properties.hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  datasource:
    url: jdbc:postgresql://localhost:1234/postgres
    username: root
    password: root
